# -*- coding: utf-8 -*-
"""Aswatha.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbbxcX51tgjjgd1Pf67ky8mPqdXFARzu
"""

import random

def number_guessing_game():
    print("Welcome to the Number Guessing Game!")
    print("I'm thinking of a number between 1 and 100...")

    secret_number = random.randint(1, 100)
    attempts = 0

    while True:
        try:
            guess = int(input("Take a guess: "))
            attempts += 1

            if guess < secret_number:
                print("Too low! Try again.")
            elif guess > secret_number:
                print("Too high! Try again.")
            else:
                print(f"Congratulations! You guessed it in {attempts} tries.")
                break

        except ValueError:
            print("Please enter a valid number.")

# Run the game
number_guessing_game()